# Generated by Django 3.2.19 on 2023-05-23 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GenomeCharacteristics',
            fields=[
                ('snp_id', models.TextField(primary_key=True, serialize=False)),
                ('snp_name', models.TextField()),
                ('characteristics', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='LifestyleInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.TextField()),
                ('snp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.genomecharacteristics')),
            ],
        ),
    ]
