# Generated by Django 4.2.1 on 2023-05-24 00:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SNPGenotype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField(choices=[('Normal', '정상'), ('Unnormal', '비정상')])),
                ('genotype', models.TextField()),
                ('snp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.genomecharacteristics')),
            ],
        ),
    ]
