# Generated by Django 4.2.1 on 2023-05-24 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_snpgenotype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snpgenotype',
            name='type',
        ),
    ]
